### ISSUE TITLE
Name collides with erlang UUID package

### ISSUE THREAD

**Issue by jfrolich** [zyro/elixir-uuid#24]
The name of this hex package collides with the erlang package: https://github.com/avtobiff/erlang-uuid. Which is widely used in the erlang community. When any erlang dependency uses that package, and another dependency depends on this package, the dependencies cannot be resolved :(

**Comment by zyro** [comment]
I've run into this myself as well, also colliding with https://github.com/okeuday/uuid. Elixir has no way to handle duplicate app names.

Any thoughts on how to handle this?

**Comment by jfrolich** [comment]
Yeah, I also first thought it could be handled by Elixir itself:
https://github.com/elixir-lang/elixir/issues/5232
I think the best way to handle is to change the app name of this uuid to something more unique. (elixir_uuid)? Looks like the only way to resolve it. However it breaks backwards compatibility.

**Comment by laibulle** [comment]
https://github.com/elixir-lang/elixir/issues/5232

**Comment by NobbZ** [comment]
Then make it a major version bump. Or rerelease as `:ex_uuid` and deprecate the old `:uuid` package.

This bug is open for ~18 months now. There have been 3 or 4 PATCH-releases since then.

None of this has mentioned the problem.

Questions because of this name clash occur on a regular base on the elixirforum. Often the only solution is to drop some dependencies and replace them by other ones which do not rely on one of the both UUID implementations (or their forks).

In my opinion the rename is less painfull in the long term then making your users angry because of breaking dep-trees.

**Comment by zyro** [comment]
Tagged and released as [`1.2.0`](https://github.com/zyro/elixir-uuid/tree/v1.2.0).
